# Generated by Django 6.0.7 on 2026-07-25 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'saved queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedMoment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_moments', to='core.utterance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
