# Generated by Django 6.0.7 on 2026-07-25 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('avatar_color', models.CharField(max_length=7)),
                ('voiceprint_enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('ambient', 'Ambient'), ('meeting', 'Meeting'), ('dictation', 'Dictation')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('sync_state', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('local', 'Local')], default='local', max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('is_seeded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='sessions', to='core.person')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions', models.ManyToManyField(blank=True, related_name='threads', to='core.session')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('offset_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='core.session')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utterances', to='core.person')),
            ],
            options={
                'ordering': ['offset_ms'],
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('commitment', 'Commitment'), ('decision', 'Decision'), ('question', 'Question'), ('figure', 'Figure')], max_length=20)),
                ('due_hint', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owed_extractions', to='core.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='core.session')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='core.utterance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
